name: ArchiverCommon

on: [pull_request, workflow_dispatch]

jobs:
  linux:
    uses: ./.github/workflows/build-docker.yml
    with:
      workflow: ${{ github.workflow }}

  windows:
    uses: ./.github/workflows/build-windows.yml
    with:
      workflow: ${{ github.workflow }}